name: Build plan (MVP)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mvp:
    name: MVP integration tests
    uses: javierdelapuente/mvp-workflows/.github/workflows/mvp-integration-tests.yaml@main
