name: MVP integration tests

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mvp:
    name: MVP integration tests
    uses: javierdelapuente/mvp-workflows/.github/workflows/mvp-integration-tests.yaml@main
